[2025-09-07T05:24:59.301+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql manual__2025-09-07T05:24:55.549977+00:00 [queued]>
[2025-09-07T05:24:59.316+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql manual__2025-09-07T05:24:55.549977+00:00 [queued]>
[2025-09-07T05:24:59.317+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:24:59.337+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_sql> on 2025-09-07 05:24:55.549977+00:00
[2025-09-07T05:24:59.353+0000] {standard_task_runner.py:60} INFO - Started process 85 to run task
[2025-09-07T05:24:59.361+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_sql', 'manual__2025-09-07T05:24:55.549977+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp7ey6il5r']
[2025-09-07T05:24:59.365+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask extract_sql
[2025-09-07T05:24:59.454+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_sql manual__2025-09-07T05:24:55.549977+00:00 [running]> on host 0f971f9b02fb
[2025-09-07T05:24:59.828+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-09-07T05:24:55.549977+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-07T05:24:55.549977+00:00'
[2025-09-07T05:24:59.830+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:25:00.005+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:25:00.148+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:25:00.225+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:25:00.265+0000] {python.py:202} INFO - Done. Returned value was: ['data/2025-09-07/sql/agencias.csv', 'data/2025-09-07/sql/clientes.csv', 'data/2025-09-07/sql/colaborador_agencia.csv', 'data/2025-09-07/sql/colaboradores.csv', 'data/2025-09-07/sql/contas.csv', 'data/2025-09-07/sql/propostas_credito.csv']
[2025-09-07T05:25:00.291+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_sql, execution_date=20250907T052455, start_date=20250907T052459, end_date=20250907T052500
[2025-09-07T05:25:00.336+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T05:25:00.355+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
