[2025-09-07T05:11:18.736+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql manual__2025-09-07T05:11:15.628030+00:00 [queued]>
[2025-09-07T05:11:18.752+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql manual__2025-09-07T05:11:15.628030+00:00 [queued]>
[2025-09-07T05:11:18.753+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:11:18.776+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_sql> on 2025-09-07 05:11:15.628030+00:00
[2025-09-07T05:11:18.785+0000] {standard_task_runner.py:60} INFO - Started process 82 to run task
[2025-09-07T05:11:18.791+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_sql', 'manual__2025-09-07T05:11:15.628030+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp4m2x308m']
[2025-09-07T05:11:18.796+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask extract_sql
[2025-09-07T05:11:18.890+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_sql manual__2025-09-07T05:11:15.628030+00:00 [running]> on host eb2538915ebb
[2025-09-07T05:11:19.004+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-09-07T05:11:15.628030+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-07T05:11:15.628030+00:00'
[2025-09-07T05:11:19.008+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:11:19.251+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:11:19.644+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:11:19.704+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:11:19.766+0000] {python.py:202} INFO - Done. Returned value was: ['data/2025-09-07/sql/agencias.csv', 'data/2025-09-07/sql/clientes.csv', 'data/2025-09-07/sql/colaborador_agencia.csv', 'data/2025-09-07/sql/colaboradores.csv', 'data/2025-09-07/sql/contas.csv', 'data/2025-09-07/sql/propostas_credito.csv']
[2025-09-07T05:11:19.804+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_sql, execution_date=20250907T051115, start_date=20250907T051118, end_date=20250907T051119
[2025-09-07T05:11:19.853+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T05:11:19.886+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
