[2025-09-07T05:11:18.740+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:11:18.756+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:11:18.757+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:11:18.777+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_csv> on 2025-09-06 04:35:00+00:00
[2025-09-07T05:11:18.785+0000] {standard_task_runner.py:60} INFO - Started process 83 to run task
[2025-09-07T05:11:18.792+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_csv', 'scheduled__2025-09-06T04:35:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpczvieg2m']
[2025-09-07T05:11:18.797+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask extract_csv
[2025-09-07T05:11:18.905+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [running]> on host eb2538915ebb
[2025-09-07T05:11:19.233+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T04:35:00+00:00'
[2025-09-07T05:11:19.235+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:11:19.676+0000] {python.py:202} INFO - Done. Returned value was: data/2025-09-06/csv/transacoes.csv
[2025-09-07T05:11:19.709+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_csv, execution_date=20250906T043500, start_date=20250907T051118, end_date=20250907T051119
[2025-09-07T05:11:19.770+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T05:11:19.801+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-07T05:16:28.015+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:16:28.029+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:16:28.031+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:16:28.045+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_csv> on 2025-09-06 04:35:00+00:00
[2025-09-07T05:16:28.056+0000] {standard_task_runner.py:60} INFO - Started process 84 to run task
[2025-09-07T05:16:28.062+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_csv', 'scheduled__2025-09-06T04:35:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpnz6q_5lz']
[2025-09-07T05:16:28.068+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask extract_csv
[2025-09-07T05:16:28.153+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [running]> on host 31f05607063d
[2025-09-07T05:16:28.525+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T04:35:00+00:00'
[2025-09-07T05:16:28.527+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:16:28.851+0000] {python.py:202} INFO - Done. Returned value was: data/2025-09-06/csv/transacoes.csv
[2025-09-07T05:16:28.889+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_csv, execution_date=20250906T043500, start_date=20250907T051628, end_date=20250907T051628
[2025-09-07T05:16:28.957+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T05:16:28.992+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-07T05:24:59.304+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:24:59.316+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:24:59.317+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:24:59.332+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_csv> on 2025-09-06 04:35:00+00:00
[2025-09-07T05:24:59.340+0000] {standard_task_runner.py:60} INFO - Started process 83 to run task
[2025-09-07T05:24:59.344+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_csv', 'scheduled__2025-09-06T04:35:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp3u_a4iko']
[2025-09-07T05:24:59.348+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask extract_csv
[2025-09-07T05:24:59.442+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [running]> on host 0f971f9b02fb
[2025-09-07T05:24:59.819+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T04:35:00+00:00'
[2025-09-07T05:24:59.822+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:24:59.826+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 36, in extract_csv
    df = pd.read_csv('/opt/airflow/csv_file/transacoes.csv')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/csv_file/transacoes.csv'
[2025-09-07T05:24:59.843+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=extract_csv, execution_date=20250906T043500, start_date=20250907T052459, end_date=20250907T052459
[2025-09-07T05:24:59.861+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task extract_csv ([Errno 2] No such file or directory: '/opt/airflow/csv_file/transacoes.csv'; 83)
[2025-09-07T05:24:59.883+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-07T05:24:59.908+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-07T05:31:29.819+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:31:29.830+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:31:29.831+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:31:29.852+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_csv> on 2025-09-06 04:35:00+00:00
[2025-09-07T05:31:29.860+0000] {standard_task_runner.py:60} INFO - Started process 83 to run task
[2025-09-07T05:31:29.864+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_csv', 'scheduled__2025-09-06T04:35:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpwk02sb9j']
[2025-09-07T05:31:29.871+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask extract_csv
[2025-09-07T05:31:29.947+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_csv scheduled__2025-09-06T04:35:00+00:00 [running]> on host 42774f68c6e3
[2025-09-07T05:31:30.305+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T04:35:00+00:00'
[2025-09-07T05:31:30.307+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:31:30.866+0000] {python.py:202} INFO - Done. Returned value was: data/2025-09-06/csv/transacoes.csv
[2025-09-07T05:31:30.892+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_csv, execution_date=20250906T043500, start_date=20250907T053129, end_date=20250907T053130
[2025-09-07T05:31:30.927+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T05:31:30.955+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
